# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mojotools',
                'doc_host': 'https://CarloLepelaars.github.io',
                'git_url': 'https://github.com/CarloLepelaars/mojotools',
                'lib_path': 'mojotools'},
  'syms': { 'mojotools.mojoexporter': { 'mojotools.mojoexporter.MojoExport': ('mojoexporter.html#mojoexport', 'mojotools/mojoexporter.py'),
                                        'mojotools.mojoexporter.MojoExport.end': ( 'mojoexporter.html#mojoexport.end',
                                                                                   'mojotools/mojoexporter.py'),
                                        'mojotools.mojoexporter.mojo': ('mojoexporter.html#mojo', 'mojotools/mojoexporter.py'),
                                        'mojotools.mojoexporter.synth_main': ( 'mojoexporter.html#synth_main',
                                                                               'mojotools/mojoexporter.py')}}}
