# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mojotools',
                'doc_host': 'https://CarloLepelaars.github.io',
                'git_url': 'https://github.com/CarloLepelaars/mojotools',
                'lib_path': 'mojotools'},
  'syms': {'mojotools.core': {'mojotools.core.foo': ('core.html#foo', 'mojotools/core.py')}}}
